export interface AccesorioSeed {
  codigo: string;
  nombre: string;
  cantidad: number;
}

export const accesoriosSeed: AccesorioSeed[] = [
  {
    codigo: 'CP-420-1-NE',
    nombre: 'cofre plastico modelo1 negro',
    cantidad: 760,
  },
  {
    codigo: 'CP-420-1-LI',
    nombre: 'cofre plastico modelo1 lila',
    cantidad: 800,
  },
  {
    codigo: 'CP-420-1-AZ',
    nombre: 'cofre plastico modelo1 azul',
    cantidad: 790,
  },
  {
    codigo: 'CP-420-1-PR',
    nombre: 'cofre plastico modelo1 palo de rosa',
    cantidad: 300,
  },
  {
    codigo: 'CP-420-2-NE',
    nombre: 'cofre plastico modelo 2 negro',
    cantidad: 1300,
  },
  {
    codigo: 'CP-420-2-LI',
    nombre: 'cofre plastico modelo 2 lila',
    cantidad: 1300,
  },
  {
    codigo: 'CP-420-2-AZ',
    nombre: 'cofre plastico modelo 2 azul',
    cantidad: 1360,
  },
  {
    codigo: 'CP-420-2-PR',
    nombre: 'cofre plastico modelo 2 palo de rosa',
    cantidad: 500,
  },
  {
    codigo: 'CP-420-3-NE',
    nombre: 'cofre plastico modelo 3 negro',
    cantidad: 1285,
  },
  {
    codigo: 'CP-420-3-LI',
    nombre: 'cofre plastico modelo 3 lila',
    cantidad: 1315,
  },
  {
    codigo: 'CP-420-3-AZ',
    nombre: 'cofre plastico modelo 3 azul',
    cantidad: 1330,
  },
  {
    codigo: 'CP-420-3-PR',
    nombre: 'cofre plastico modelo 3 palo de rosa',
    cantidad: 500,
  },
  {
    codigo: 'CP-420-4-NE',
    nombre: 'cofre plastico modelo 4 negro',
    cantidad: 1220,
  },
  {
    codigo: 'CP-420-4-PL',
    nombre: 'cofre plastico modelo 4 plomo',
    cantidad: 740,
  },
  {
    codigo: 'CP-420-5-NE',
    nombre: 'cofre plastico modelo 5 negro',
    cantidad: 688,
  },
  {
    codigo: 'CP-420-5-LI',
    nombre: 'cofre plastico modelo 5 lila',
    cantidad: 559,
  },
  {
    codigo: 'CP-420-5-AZ',
    nombre: 'cofre plastico modelo 5 azul',
    cantidad: 515,
  },
  {
    codigo: 'CP-039-10-CB1',
    nombre: 'cofre plastico cuadrado combinados 1 (bolsaX10)',
    cantidad: 1340,
  },
  {
    codigo: 'CP-039-11-CB2',
    nombre: 'cofre plastico redondo combinados 2 (bolsaX10)',
    cantidad: 360,
  },
  {
    codigo: 'CP-039-12-CB3',
    nombre: 'cofre plastico redondo combinados 3 (bolsaX10)',
    cantidad: 900,
  },
  {
    codigo: 'CP-IM-6-CB1',
    nombre: 'cofre plastico de mica combinacion 1 (bolsaX20)',
    cantidad: 1800,
  },
  {
    codigo: 'CP-IM-6-CB2',
    nombre: 'cofre plastico de mica combinacion 2 (bolsaX40)',
    cantidad: 80,
  },
  {
    codigo: 'CD-CV-CF',
    nombre: 'cofre duro contacto visual café',
    cantidad: 40,
  },
  {
    codigo: 'CD-CV-NE',
    nombre: 'cofre duro contacto visual negro',
    cantidad: 200,
  },
  {
    codigo: 'CD-SD-420-6-NE',
    nombre: 'cofre duro sin diseño negro',
    cantidad: 960,
  },
  {
    codigo: 'CD-SD-420-7-CF',
    nombre: 'cofre duro sin diseño café',
    cantidad: 370,
  },
  {
    codigo: 'CD-SD-420-8-AZ',
    nombre: 'cofre duro sin diseño azul',
    cantidad: 0,
  },
  {
    codigo: 'CD-SD-420-9-GUI',
    nombre: 'cofre duro sin diseño guindo',
    cantidad: 0,
  },
  {
    codigo: 'CD-CD-039-7-NÑ',
    nombre: 'cofre duro con diseño para niños',
    cantidad: 800,
  },
  {
    codigo: 'CP-CD-039-6-MK',
    nombre: 'cofre duro con diseño mickey (cajaX10)',
    cantidad: 1280,
  },
  {
    codigo: 'CD-CD-9-MÑ',
    nombre: 'cofre duro con diseño muñecas (bolsasX10)',
    cantidad: 800,
  },
  {
    codigo: 'CD-CD-3-FL',
    nombre: 'cofre duro con diseño flores (bolsasX10)',
    cantidad: 150,
  },
  {
    codigo: 'CD-CD-7-LT',
    nombre: 'cofre duro con diseño letras (bolsasX10)',
    cantidad: 200,
  },
  { codigo: 'CD-420-9A-NE', nombre: 'cofre duro orange negro', cantidad: 7050 },
  {
    codigo: 'CD-420-9B-NE',
    nombre: 'cofre duro crystal negro',
    cantidad: 6357,
  },
  {
    codigo: 'CD-420-10-VE',
    nombre: 'cofre duro con tapa curvo verde',
    cantidad: 970,
  },
  {
    codigo: 'CD-420-10-AZ',
    nombre: 'cofre duro con tapa curvo azul',
    cantidad: 1000,
  },
  {
    codigo: 'CD-420-10-PL',
    nombre: 'cofre duro con tapa curvo plomo',
    cantidad: 1000,
  },
  {
    codigo: 'CD-420-11-VE',
    nombre: 'cofre duro con tapa recta verde',
    cantidad: 999,
  },
  {
    codigo: 'CD-420-11-AZ',
    nombre: 'cofre duro con tapa recta azul',
    cantidad: 1000,
  },
  {
    codigo: 'CD-420-11-PL',
    nombre: 'cofre duro con tapa recta plomo',
    cantidad: 1000,
  },
  { codigo: 'CD-039-3-SOL', nombre: 'cofre duro solar', cantidad: 60 },
  {
    codigo: 'ESLC-10-CAR',
    nombre: 'estuche solar de lona con cierre tipo carrito',
    cantidad: 820,
  },
  {
    codigo: 'ESLC-4-CB',
    nombre: 'estuche solar de lona con cierre combinado (punoX20)',
    cantidad: 440,
  },
  {
    codigo: 'ESLC-CD-13-RJ',
    nombre: 'estuche solar de lona con cierre diseño letras rojo',
    cantidad: 100,
  },
  {
    codigo: 'ESLC-CD-13-LI',
    nombre: 'estuche solar de lona con cierre diseño letras lila',
    cantidad: 60,
  },
  {
    codigo: 'ESLC-CD-13-RS',
    nombre: 'estuche solar de lona con cierre diseño letras rosa',
    cantidad: 80,
  },
  {
    codigo: 'ESLC-CD-13-PL',
    nombre: 'estuche solar de lona con cierre diseño letras plomo',
    cantidad: 80,
  },
  {
    codigo: 'ESLC-CD-11-CB',
    nombre:
      'estuche solar de lona con cierre diseño flores combinado (bolsasX12)',
    cantidad: 347,
  },
  { codigo: 'EPS-NE', nombre: 'estuche pita solar negro', cantidad: 91 },
  {
    codigo: 'EPS-GAM-NE',
    nombre: 'estuche pita solar gamusa negro',
    cantidad: 100,
  },
  { codigo: 'ES-DOR', nombre: 'estuche sobre dorado', cantidad: 240 },
  { codigo: 'ES-AM', nombre: 'estuche sobre amarillo', cantidad: 100 },
  { codigo: 'ES-PL', nombre: 'estuche sobre plomo', cantidad: 120 },
  { codigo: 'ES-RS', nombre: 'estuche sobre rosa', cantidad: 120 },
  {
    codigo: '20-72',
    nombre: 'botella cilindrica larga transparente de 130 ml',
    cantidad: 15004,
  },
  {
    codigo: '20-173',
    nombre: 'botella hexagonal ancha transparente de 90 ml',
    cantidad: 9947,
  },
  {
    codigo: '20-174',
    nombre: 'botella hexagonal larga transparente de 90 ml',
    cantidad: 7200,
  },
  {
    codigo: '20-34',
    nombre: 'botella cilindrica pequeña transparente de 65 ml',
    cantidad: 5006,
  },
  {
    codigo: '20-28',
    nombre: 'botella cilindrica delgada transparente de 60 ml',
    cantidad: 14300,
  },
  {
    codigo: '20-57',
    nombre: 'botella cilindrica larga transparente de 100 ml',
    cantidad: 8697,
  },
  {
    codigo: '20-190',
    nombre: 'botella plana mediana transparente de 95 ml',
    cantidad: 8000,
  },
  {
    codigo: '20-46',
    nombre: 'botella cilindrica mediana transparente de 75 ml',
    cantidad: 1812,
  },
  {
    codigo: '20-16',
    nombre: 'botella cilindrica mediana transparente de 80 ml',
    cantidad: 1400,
  },
  { codigo: '109', nombre: 'tapa atomizador grande', cantidad: 15000 },
  { codigo: '88', nombre: 'tapa atomizador mediano-grande', cantidad: 8000 },
  { codigo: '74', nombre: 'tapa atomizador mediano', cantidad: 31839 },
  { codigo: '50', nombre: 'tapa atomizador pequeño', cantidad: 8261 },
  { codigo: 'A-T-NE', nombre: 'topes color negro (bolsa X50)', cantidad: 1700 },
  {
    codigo: 'A-T-TR',
    nombre: 'topes color transparente (bolsaX50)',
    cantidad: 1700,
  },
  { codigo: 'A-420-12-rs', nombre: 'desarmador multiuso rosa', cantidad: 10 },
  { codigo: 'A-420-12-ne', nombre: 'desarmador multiuso negro', cantidad: 10 },
  { codigo: 'A-420-12-li', nombre: 'desarmador multiuso lila', cantidad: 8 },
  { codigo: 'A-420-12-ce', nombre: 'desarmador multiuso celeste', cantidad: 7 },
  { codigo: 'A-420-12-pl', nombre: 'desarmador multiuso plomo', cantidad: 3 },
  { codigo: 'A-420-12-az', nombre: 'desarmador multiuso azul', cantidad: 11 },
  { codigo: 'A-420-12-rj', nombre: 'desarmador multiuso rojo', cantidad: 4 },
  {
    codigo: 'A-BT-CS',
    nombre: 'bolsa transparente con seguro para certificados',
    cantidad: 7,
  },
  {
    codigo: 'A-BT-C',
    nombre: 'bolsa transparente para certificados',
    cantidad: 8,
  },
  {
    codigo: 'A-BBT-M',
    nombre: 'bolsa brillante transparente mediana',
    cantidad: 30,
  },
  {
    codigo: 'A-BBT-G',
    nombre: 'bola brillante transparente grande',
    cantidad: 22,
  },
  { codigo: 'A-EE-AZ', nombre: 'espejo de mesa azul', cantidad: 19 },
  { codigo: 'A-EE-NE', nombre: 'espejo de mesa negro', cantidad: 30 },
  { codigo: 'A-EE-RJ', nombre: 'espejo de mesa rojo', cantidad: 17 },
  { codigo: 'E-IM-44-04', nombre: 'quemador de lunas', cantidad: 18 },
  { codigo: 'E-04-6-P-05', nombre: 'uveometro grande', cantidad: 9 },
  { codigo: 'E-04-6-G-06', nombre: 'uveometro pequeño', cantidad: 1 },
  { codigo: 'S-818', nombre: 'silla sin rueda clase 1 (cajaX4)', cantidad: 20 },
  { codigo: 'S-803', nombre: 'silla sin rueda clase 2 (cajaX6)', cantidad: 42 },
  {
    codigo: 'SF-108',
    nombre: 'silla flotante acolchonado con rueda',
    cantidad: 19,
  },
  {
    codigo: 'SF-IM-35',
    nombre: 'silla flotante acolchonado sin rueda',
    cantidad: 30,
  },
  { codigo: 'SF-106', nombre: 'silla flotante plano sin rueda', cantidad: 49 },
  { codigo: 'SS-E-CR', nombre: 'silla ergonomica con riñonera', cantidad: 2 },
  { codigo: 'SS-E-SR', nombre: 'silla ergonomica sin riñonera', cantidad: 2 },
  { codigo: 'SSS-E', nombre: 'sillon ergonomico', cantidad: 2 },
  { codigo: 'C', nombre: 'cafetera', cantidad: 1 },
  { codigo: 'H', nombre: 'hervidora', cantidad: 1 },
  { codigo: 'D', nombre: 'dispensador', cantidad: 6 },
  { codigo: 'CC', nombre: 'cocina', cantidad: 1 },

  { codigo: 'A-096-5', nombre: 'franela estándar simple', cantidad: 490 },
  { codigo: 'A-2018-A', nombre: 'franela microfibra', cantidad: 1362 },
  { codigo: 'A-B-13', nombre: 'contometro (pack X5)', cantidad: 2275 },
  { codigo: 'E-LD-01', nombre: 'lensontro digital', cantidad: 2 },
  { codigo: 'E-F-02', nombre: 'foroptero', cantidad: 1 },
  { codigo: 'E-C-03', nombre: 'calentador/secador', cantidad: 6 },
  { codigo: 'AB-ACB-01', nombre: 'ACC viseladora', cantidad: 2 },
  { codigo: 'A-MP-01', nombre: 'montura de prueba intermedia', cantidad: 8 },
  { codigo: 'A-MP-02', nombre: 'montura de prueba aluminio', cantidad: 9 },
  { codigo: 'A-MP-03', nombre: 'montura de prueba caro', cantidad: 9 },
  { codigo: 'E-LM-07', nombre: 'lensometro manual', cantidad: 4 },
  { codigo: 'A-CE', nombre: 'cinta de embalaje grande', cantidad: 232 },
  { codigo: 'AB-SB-02', nombre: 'seguros para biseladora', cantidad: 7 },
  { codigo: 'AB-PB-03', nombre: 'pegatina para biseladora', cantidad: 48 },
  { codigo: 'AB-BH-04', nombre: 'bomba hidraulica', cantidad: 3 },
  { codigo: 'A-MM', nombre: 'maletin negro para monturas', cantidad: 2 },
  { codigo: 'A-SH', nombre: 'set de herramientas', cantidad: 2 },
  { codigo: 'A-SD', nombre: 'set de desarmadores', cantidad: 2 },
  { codigo: 'A-EX12', nombre: 'exhibidor de lunas de 12p', cantidad: 14 },
  { codigo: 'A-EX24', nombre: 'exhibidor de lunas de 24p', cantidad: 10 },
  { codigo: 'A-MH', nombre: 'maletin de herramientas', cantidad: 2 },
  { codigo: 'A-CB', nombre: 'calibradores', cantidad: 17 },
  { codigo: 'A-DV', nombre: 'devastadores', cantidad: 15 },
  { codigo: 'A-LINT', nombre: 'linterna', cantidad: 391 },
  { codigo: 'A-VB', nombre: 'valvula de bola', cantidad: 19 },
  { codigo: 'A-TH', nombre: 'test hisaic', cantidad: 3 },
  { codigo: 'AB-PCL-05', nombre: 'perforador cortador de lunas', cantidad: 1 },
  { codigo: 'A-FUV', nombre: 'foco ultravioleta', cantidad: 145 },
  { codigo: 'BL-CRY', nombre: 'bolsa para lente crystal', cantidad: 0 },
  { codigo: 'BL-POLY', nombre: 'bolsa para lente poliblue', cantidad: 3090 },
  {
    codigo: 'CAJA-LENSOMETRO',
    nombre: 'caja vacia de lensometro digital',
    cantidad: 2,
  },
  { codigo: 'SF-SIM-NE', nombre: 'silla flotante simple negro', cantidad: 18 },
  { codigo: 'SF-SIM-AZ', nombre: 'silla flotante simple azul', cantidad: 30 },
  { codigo: 'SP-AZ', nombre: 'silla plastica azul', cantidad: 24 },
  { codigo: 'P-LC', nombre: 'lunas cristal +6-6*6 (muestras)', cantidad: 18 },
];
